### ISSUE TITLE
Speech plays twice on Single

### ISSUE THREAD

**Issue by mikeyrayvon** [interglobalvision/trophymodern-com#50]
plays once through then some sentences again.  sometimes second playback sentences are out of order.  maybe we should get rid of the sentence array strategy??

**Comment by mikeyrayvon** [comment]
this happens every time i open single

**Comment by varffs** [comment]
Can u put the exact link cuz I haven't had this at all

**Comment by varffs** [comment]
For example this link: http://www.trophymodern.com/american-diner/ is fine for me

**Comment by mikeyrayvon** [comment]
it happens to me on all of them.  it seems like the sentences are getting added to the array multiple times.  sometimes in random order.

**Comment by varffs** [comment]
not replicable
