### ISSUE TITLE
Font declaration

### ISSUE THREAD

**Issue by varffs** [interglobalvision/trophymodern-com#54]
Only one font is in named use in the css file `UniversLTStd` however this font is declared 5 times with different overwrite values and source files.

My understanding of font-face is that this is wrong, and if wrong it will be causing extra http requests and slowing css rendering

**Comment by mikeyrayvon** [comment]
this clears it up http://www.smashingmagazine.com/2013/02/setting-weights-and-styles-at-font-face-declaration/

**Comment by mikeyrayvon** [comment]
i'll go with option 3

**Comment by varffs** [comment]
Ok cool this is an interesting solution if IE8 and iPad1 are the only failing cases
